### PR TITLE
Profit per RNGMeter fixes

### LINKED ISSUE #456: Profit Per RNGMeter: Doesn't include cost for chest/start cost of slayer

### PR DESCRIPTION
**Pull request by VixidDev**
Mostly resolves #456 and #457, the slayer cost is now accounted for and the amount of loot that rng drops at each tier. Cost of dungeon chests haven't been included since there is a lot of variation of chest cost depending on the items in it.

Turns out every single slayer drop is a loss other than a Judgement Core. (obviously this feature doesn't take into account any other drops other than the RNG itself) 👍 

shortNumberFormat function also updated to work with negative numbers

### CODE REVIEW

File: src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java [hunk 1]
```diff
@@ -59,6 +61,8 @@ public class ItemTooltipRngListener {
 
 	private final Pattern SLAYER_INVENTORY_TITLE_PATTERN = Pattern.compile("(.+) RNG Meter");
 
+	private final Pattern TIER_AMOUNT = Pattern.compile("§5§o§7Tier (.+) amount: §a(\\d+).*");
```
Comment (hannibal002) [inline src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java:64]: We should start thinking about what name design we want field patterns to have. Both types have been used a similar number of times throughout the project. (THIS_FORMAT or thatFormat)

File: src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java [hunk 2]
```diff
@@ -324,6 +339,24 @@ private void runsRequired(
...
 	}
 
+	private int parseAmountFromTooltip(List<String> tooltip) {
+		Map<Integer, Integer> tierToAmount = new HashMap<>();
+
+		for (String line : tooltip) {
+			Matcher amountMatcher = TIER_AMOUNT.matcher(line);
+			if (amountMatcher.matches()) {
+				try {
+					// group(2) will get the lower bound of number of drops that is dropped from each of the tiers (i.e. if "2 to 4" we get 2)
```
Comment (hannibal002) [inline src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java:349]: I think this is a good spot to use 2 variables with helpful names instead of having a complicated looking one-liner and a comment on top.

**Review by hannibal002 — CHANGES_REQUESTED** [review]
The logic changes are looking fine to me.

File: src/main/java/io/github/moulberry/notenoughupdates/core/util/StringUtils.java [hunk 3]
```diff
@@ -85,7 +85,7 @@ public static String shortNumberFormat(BigInteger bigInteger) {
 	}
 
 	public static String shortNumberFormat(double n, int iteration) {
-		if (n < 1000) {
+		if (n < 1000 && n > -1000) {
```
Comment (romangraef) [inline src/main/java/io/github/moulberry/notenoughupdates/core/util/StringUtils.java:88]: I feel like it would be cleaner to have a just call itself like `return "-" + shortNumberFormat(-n, iteration)`

File: src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java (hunk 1 above)
Comment (VixidDev) [reply src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java:64]: I prefer using uppercase with underscores for constant like variables such as patterns, since I do believe that is the official naming convention for constant fields

**Review by romangraef — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by DeDiamondPro — APPROVED** [review]
