### PR TITLE
Fix enchanted books not working with bz keybind

### LINKED ISSUE #885: BZ keybind does not work for Enchanted Books
The displayname is "Enchanted Book"

### PR DESCRIPTION
**Pull request by Lulonaut**
closes #885

Extracts the book name from the lore of the item.
Then searches directly with /bz since enchanted books can't be in the auction house

### CODE REVIEW

File: src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java [hunk 1]
```diff
@@ -1213,7 +1213,13 @@ public void consume(int x, int y, int id) {
 							return true;
 						} else if (keyPressed == NotEnoughUpdates.INSTANCE.config.misc.openAHKeybind) {
 							String cleanName = Utils.cleanColour(item.get("displayname").getAsString()).replace("[Lvl {LVL}]", "").trim();
-							if (NotEnoughUpdates.INSTANCE.manager.auctionManager.getBazaarInfo(internalname.get()) == null) {
+
+							if (item.get("itemid").getAsString().equals("minecraft:enchanted_book")) {
```
Comment (nea89o) [inline src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java:1217]: Checking just for itemid will break for items that render as an enchanted book, but are *not* an enchanted book. For example the experience artifact.

**Review by nea89o — CHANGES_REQUESTED** [review]

**Review by nea89o — APPROVED** [review]

**Review by DeDiamondPro — APPROVED** [review]
