### PR TITLE
fix: abiphone favorites showing in /show

### LINKED ISSUE #930: AbiphoneFavourites: Show in /show
image

### PR DESCRIPTION
**Pull request by GrowlingGrizzly**
Uses item slot in show menu and sets wrong inventory if it is an abiphone

closes #930

image

image

### CODE REVIEW

File: src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneFavourites.java [hunk 1]
```diff
@@ -50,6 +50,7 @@ public class AbiphoneFavourites {
 
 	private static final AbiphoneFavourites INSTANCE = new AbiphoneFavourites();
 	private long lastClick = 0L;
+	private ItemStack checkShowSlot = null;
```
Comment (nea89o) [inline src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneFavourites.java:53]: Since the item stack is only ever used for one specific boolean check, a boolean could be used here.
Also: the name is somewhat lacking. Consider maybe `isInShowMenu`.

File: src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneFavourites.java [hunk 2]
```diff
@@ -204,10 +205,15 @@ public boolean onRenderStack(ItemStack stack) {
...
 	public void onDrawBackground(GuiContainerBackgroundDrawnEvent event) {
-		if (isWrongInventory()) return;
+		if (!NotEnoughUpdates.INSTANCE.hasSkyblockScoreboard()
+			|| !NotEnoughUpdates.INSTANCE.config.misc.abiphoneFavourites
+			|| Utils.getOpenChestName().equals("Abiphone Shop")
+			|| !Utils.getOpenChestName().startsWith("Abiphone ")) return;
 
 		GuiContainer container = event.getContainer();
 
+		checkShowSlot = container.inventorySlots.getSlot(13).getStack();
```
Comment (nea89o) [inline src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneFavourites.java:215]: If you are going to change something anyway, you could also split up `13` into `1*9 + 4` to more easily show which row/column you target.

**Review by nea89o — CHANGES_REQUESTED** [review]
Works great!

**Review by nea89o — APPROVED** [review]
