### PR TITLE
Changed gatherJacobData to a regex and fixed a NFE

### LINKED ISSUE #808: FarmingSkillOverlay: NumberFormatException from gatherJacobData
https://hst.sh/raw/ruhofowebu

### PR DESCRIPTION
**Pull request by jani270**
Fixed #808

### CODE REVIEW

File: src/main/java/io/github/moulberry/notenoughupdates/overlays/FarmingSkillOverlay.java [hunk 1]
```diff
@@ -136,14 +138,20 @@ private void gatherJacobData() {
 		inJacobContest = false;
 		if (isJacobTime()) {
 			int timeLeftInContest = (20 * 60) - ((int) ((System.currentTimeMillis() % 3600000 - 900000) / 1000));
+			Pattern pattern = Pattern.compile(Utils.cleanColour(
```
Comment (NopoTheGamer) [inline src/main/java/io/github/moulberry/notenoughupdates/overlays/FarmingSkillOverlay.java:141]: shouldnt you not pattern compile every tick?

**Review by NopoTheGamer — CHANGES_REQUESTED** [review]

**Review by Lulonaut — DISMISSED** [review]

File: src/main/java/io/github/moulberry/notenoughupdates/overlays/FarmingSkillOverlay.java [hunk 2]
```diff
@@ -88,6 +90,9 @@ public class FarmingSkillOverlay extends TextOverlay {
 
 	private String skillType = "Farming";
 
+	private static final Pattern CONTEST_AMOUNT_PATTERN = Pattern.compile(
+		" (Collected|(BRONZE|SILVER|GOLD|PLATINUM|DIAMOND) with) (?<amount>.*)");
```
Comment (nea89o) [inline src/main/java/io/github/moulberry/notenoughupdates/overlays/FarmingSkillOverlay.java:94]: Can we be more explicit about the amount group and what it can contain? We have a try catch, but creating stacktraces often can lead to performance degradation

**Review by nea89o — CHANGES_REQUESTED** [review]

**Review by nea89o — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]
